### ISSUE TITLE
What is the advantage compared to the kornia?

### ISSUE THREAD

**Issue by hirune924** [PhoenixDL/rising#104]
**Description**
The README says that the difference between kornia and rising is that rising supports Volumetric data. But it seems that kornia also has a feature called geometry.
https://kornia.readthedocs.io/en/latest/geometry.html

Does this mean that kornia supports Volumetric Data? Or am I misunderstanding something about Volumetric Data?

**Comment by justusschock** [comment]
Hi :)

`kornia.geometry` mainly focuses on camera intrinsics and depth cameras (or depth estimation from stereo imaging). 
With `rising` we focus on volumetric data like MRI or CT scans, which always include a complete volume.

Hope this helps

**Comment by hirune924** [comment]
Thank you! I understand!

**Comment by edgarriba** [comment]
camera instrinsics and depth it's a small just a part in geometry. There's also support for many tensors features transformations - affine2d, homography, depth and very soon projective for transforming volumes using 3d transformations. Besides, in geometry we have many conversion for transformation formats like quaternions, rotation matrices, points and and bounding boxes, epipolar geometrry and subpixel accuracy operators for 2d and 3d. Kornia domain not specific, it's just a replica of opencv functionality.
