### ISSUE TITLE
[Bug] Wrong point/image trafo

### ISSUE THREAD

**Issue by NKPmedia** [PhoenixDL/rising#109]
**Description**
@mibaumgartner 
The point transformation has to be the inverse of the image transformation.

**Environment**
* OS: 
* Python version:
* `rising` version 0.2.0.post0
* How did you install `rising`? [ pip]

**Reproduction**
```
imgT = parametrize_matrix(rotation=30, scale=1, translation=0, image_transform=True, batchsize=1, ndim=2)
pointT = parametrize_matrix(rotation=30, scale=1, translation=0, image_transform=False, batchsize=1, ndim=2)
print("img Trafo A:")
print(to_homogeneus_matrix(imgT))
print("point Trafo B:")
print(to_homogeneus_matrix(pointT))
print("C should be equal to B:")
print(to_homogeneus_matrix(imgT).inverse())
```
The code works if the points are not xy but yx because 
`matrix_revert_coordinate_order(pointT)` produces matrix C.

More over the permutation of the sub transformations if wrong because it changes with the inverse operation.

**Comment by mibaumgartner** [comment]
Dear @NKPmedia, thank you for this Issue.
I think you might be right and we forgot to add `image_transform` to the rotation, even though i think it was visually correct. Can you submit/ Are you willing to submit a PR? :)

**Comment by NKPmedia** [comment]
Give me a day :D Do you have tests for this part of the code?

**Comment by mibaumgartner** [comment]
Nice, thanks! 👍 There are quite a lot of shape and sanity checks ([here](https://github.com/PhoenixDL/rising/blob/master/tests/transforms/functional/test_affine.py)) for the affine transformations. Would be great if you could add some small tests so this won't happen again :)
