### ISSUE TITLE
still maintain this framework?

### ISSUE THREAD

**Issue by jizongFox** [PhoenixDL/rising#125]
**Description**
Hello, thanks for this framework.  I see clearly the advantage of this repo compared with counterparts such as torchIO. 

I saw that you have stopped developing it for a long time, was it because your team switched to another framework to replace it? 

**Environment (Optionally)**

- OS:
- Python version:
- `rising` version

**Comment by jizongFox** [comment]
Hello, I have fixed most of the bugs in my forked version, but I have to, unfortunately, change the main concept architecture of the project, in order to adapt to stricter needs. I think this would not be suitable for a PR. My modified version is now working properly and has been involved in multiple projects with GPU acceleration for medical image segmentation. 

Best regards,
Jizong

**Comment by justusschock** [comment]
Hi,

Are the fixes related to the change of concept? Would you be able to submit those fixes individually?

Best,
Justus

**Comment by jizongFox** [comment]
You may want to have a look at the differences that I made from https://github.com/jizongFox/rising/pull/16. 

Too much has been changed. I cannot really separate the commits. 

Hope my design helps to some extend.
