### ISSUE TITLE
[Question] Citation?

### ISSUE THREAD

**Issue by rijobro** [PhoenixDL/rising#126]
Hi, do you have a preferred way to cite this work? I've checked the README, readthedocss, old github issues, etc. and haven't seen it mentioned. Apologies if I've missed it somewhere.

Thanks in advance

**Comment by justusschock** [comment]
Hi,

Thanks for asking. I have added a citation.cff file to this repository using the latest zenodo release.
You should find it at the repository root. It also enables the "cite this repository" functionality on github.

**Comment by rijobro** [comment]
Great, thanks!
