### ISSUE TITLE
[FeatureRequest] Improve Pull Request Template

### ISSUE THREAD

**Issue by mibaumgartner** [PhoenixDL/rising#18]
**Description**
This issue is intended to provide a forum to improve our PR template

**Proposals**

Additional todos:
* update codeowners.md
* update changelog

Furthermore, I would like to propose to structure the todos a little bit more. Something like:
`Developer` (the person who implements the PR), `RisingMember` (someone who has rights to add lables, projects, modify codeowner , chagelog ... )

We could also introduce a reviewer section where we add some points which every reviewer should check (probably with an link to our contribution guideline)

Do you have additional points or do not like any of the above? @haarburger  @justusschock

**Comment by haarburger** [comment]
I tend to appreciate your suggestions. On the other side, if the whole project is too organised formally, it might appear intimidating to potential contributors..

**Comment by mibaumgartner** [comment]
Yes, that may be a risk. On the other hand, I do not think it is beneficial to hide the process which every pr should go through anyway. When splitting the tasks we could use collapsible sections to hide the `RisingMember` and `Reviewer` tasks which would be less intimidating.
