### ISSUE TITLE
[FeatureRequest] GPU transforms

### ISSUE THREAD

**Issue by mibaumgartner** [PhoenixDL/rising#22]
**Description**
Currently, the data loader can not execute transformations on the GPU due to multiprocessing and some pickling issues. A workaround is to manually apply the transforms during training before the networks gets the data.

**Proposal**
How could the feature be implemented? 
Native support of GPU transformations for the data loader.

**Comment by mibaumgartner** [comment]
IMO we don't want multiprocessing for the GPU. I did some experiments and it uses way to much memory  and is not for what GPUs are meant for in the first place. 

I think we need to introduce some point in the data loader where the preprocessed data from the CPU is collected and only transform a single batch at the time on the gpu. The workflow would look roughly like this:

```
data => cpu processing
data => cpu processing => collect => when batch requested: put on target gpu => transform => network
data => cpu processing
```
I could imagine the "request batch" part could be realised by python coroutines :)

**Comment by justusschock** [comment]
The problem is, that it creates a separate cuda context for each worker process. However I'm not sure if the approach with coroutines is the best one or if we just implement a queueing system so that we only use one process for GPU transforms and multiple processes for loading and CPU transforms
