### ISSUE TITLE
[Bug] Pillow and Torchvision Incompatibility

### ISSUE THREAD

**Issue by justusschock** [PhoenixDL/rising#28]
**Description**
The notebooks can't run with the latest pillow, since `torchvision` checks for `PILLOW_VERSION` which was removed in the latest pillow release (https://pillow.readthedocs.io/en/stable/releasenotes/7.0.0.html#pillow-version-constant)

For now I restricted the pillow version to the previous release, but we should upgrade, once the new torch vision is out.

**Comment by hugovk** [comment]
The torchvision fix is due out early next week  (https://github.com/pytorch/vision/issues/1712):

> We will be releasing a new version of PyTorch and torchvision early next week, so this should be soon fixed.

**Comment by hugovk** [comment]
[torchvision v0.5.0](https://github.com/pytorch/vision/releases/tag/v0.5.0) has been released with the fix:

1. Require `torchvision>=0.5.0`
2. If Pillow was temporarily pinned, remove the pin

**Comment by mibaumgartner** [comment]
Fixed in 7a1c8ba569a6ff6512cfd9bc0b2cf30f6aa107b4 :)
