### ISSUE TITLE
[FeatureRequest] Lightning Example

### ISSUE THREAD

**Issue by mibaumgartner** [PhoenixDL/rising#63]
Create an example notebook with pytorch lightning
Either use a torchvision dataset or MedMnist (could be a cool alternative)

**Comment by justusschock** [comment]
I'd prefer MedMnist

**Comment by mibaumgartner** [comment]
@justusschock 
This will probably be our main example because it is very easy to use (we can add additional features to other notebooks in the future): I think we should put in a bit more effort into this one add some additional features:
- [ ] Make it easy to switch between CPU and GPU execution and report training time for both in the text (a real cpu vs gpu benchmark could follow in the future but we should use volumetric data for that to showcase the computational benefits)
- [ ] Showcase multiple augmentation pipelines (at least one lightweight one and one very extensive) and report results for classification
